#!/bin/sh
set -e
case "$1" in
  remove|deconfigure)
    if [ -d /run/systemd/system ]; then
        systemctl stop onv-provider.service || true
        systemctl disable onv-provider.service >/dev/null 2>&1 || true
    fi
    ;;
esac
exit 0
