#!/usr/bin/env python3
"""The package's version: the content hash of what it is built from (omnuv's
modular design, A5).

    packaging/version.py <root> <dep-info>...           <crate>+c<hash12>
    packaging/version.py --list <root> <dep-info>...    the inputs, one per line

The version was `<crate>+g<commit>`, so every commit was a new package, a
test-only one included, and every package restarted the agent. It is now
`<crate>+c<hash12>`, where the hash is over the bytes the package is built
from, and nothing else:

    what cargo read    every file the release binaries were compiled from, as
                       their dep-info lists it (target/release/<bin>.d, and
                       onv-workloadd's under target/musl), which the build
                       wrote inside its container, where this tree is /w
    what pins the rest Cargo.lock, which pins every registry and git crate by
                       checksum or revision, so their sources, outside /w, are
                       not hashed; every Cargo.toml in the workspace; and
                       .cargo/config.toml or rust-toolchain(.toml) if present
    what is shipped    packaging/build-deb.sh, which names the toolchain image
                       and writes the control file, every file under
                       packaging/deb, README.md and LICENSE

A file under tests/, or a `#[cfg(test)]` module in its own file, is read by no
release build, so a commit touching only those keeps the version; a change to
a source file, a unit file or a maintainer script moves it. Files under /w's
target/ are generated from the inputs above and are skipped. A listed input
that is missing under <root> is refused: the dep-info is from another tree.

The hash is sha256 over `<sha256>  <path>\\n` for each input, sorted by its
path relative to <root>, so a renamed file moves it as an edited one does.
tests/packaging/version_test.py holds it to both directions.
"""

import hashlib
import pathlib
import re
import sys

BUILD_ROOT = "/w"  # where build-deb.sh mounts the tree


def dep_paths(text: str) -> list[str]:
    """Every prerequisite in a make-style dep-info file, unescaped."""
    paths = []
    for line in text.replace("\\\n", " ").splitlines():
        # `target: prereq prereq`; a path's own spaces are escaped as `\ `.
        m = re.match(r"^((?:[^:\\]|\\.)+):(.*)$", line)
        if not m:
            continue
        for tok in re.findall(r"(?:\\.|[^\s\\])+", m.group(2)):
            paths.append(re.sub(r"\\(.)", r"\1", tok))
    return paths


def inputs(root: pathlib.Path, depinfos: list[pathlib.Path]) -> list[str]:
    """The inputs, relative to root, sorted."""
    found: set[str] = set()
    for d in depinfos:
        if not d.is_file():
            # No build has run in this tree, or not this one's: said, never a
            # traceback (omnuv's agent-package-current.yml prints it).
            sys.exit(f"version: no dep-info at {d}; build the package first")
        listed = dep_paths(d.read_text())
        if not listed:
            sys.exit(f"version: {d} lists no input; it is not a dep-info file")
        for p in listed:
            if not p.startswith(BUILD_ROOT + "/"):
                continue  # a registry or git crate, pinned by Cargo.lock
            rel = p[len(BUILD_ROOT) + 1:]
            if rel == "target" or rel.startswith("target/"):
                continue  # generated by a build script from pinned inputs
            found.add(rel)
    fixed = ["Cargo.lock", "Cargo.toml", "packaging/build-deb.sh", "README.md", "LICENSE"]
    found.update(fixed)
    for name in [".cargo/config.toml", ".cargo/config", "rust-toolchain", "rust-toolchain.toml"]:
        if (root / name).is_file():
            found.add(name)
    for manifest in sorted(root.glob("crates/*/Cargo.toml")):
        found.add(manifest.relative_to(root).as_posix())
    for f in sorted((root / "packaging/deb").rglob("*")):
        if f.is_file():
            found.add(f.relative_to(root).as_posix())
    missing = sorted(r for r in found if not (root / r).is_file())
    if missing:
        sys.exit(f"version: inputs missing under {root}: {', '.join(missing[:5])}")
    return sorted(found)


def crate_version(root: pathlib.Path) -> str:
    m = re.search(r'(?m)^version *= *"([^"]+)"', (root / "Cargo.toml").read_text())
    if not m:
        sys.exit("version: Cargo.toml names no version")
    return m.group(1)


def version(root: pathlib.Path, depinfos: list[pathlib.Path]) -> str:
    h = hashlib.sha256()
    for rel in inputs(root, depinfos):
        h.update(f"{hashlib.sha256((root / rel).read_bytes()).hexdigest()}  {rel}\n".encode())
    return f"{crate_version(root)}+c{h.hexdigest()[:12]}"


def main(argv: list[str]) -> None:
    listing = bool(argv) and argv[0] == "--list"
    if listing:
        argv = argv[1:]
    if len(argv) < 2:
        sys.exit(__doc__.split("\n\n")[1])
    root = pathlib.Path(argv[0]).resolve()
    depinfos = [pathlib.Path(a) for a in argv[1:]]
    if listing:
        print("\n".join(inputs(root, depinfos)))
    else:
        print(version(root, depinfos))


if __name__ == "__main__":
    main(sys.argv[1:])
