name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test
      - name: Lints
        run: cargo clippy --all-targets -- -D warnings
